/* global describe it */

'use strict'

const chai = require('chai')
const should = chai.should()
const assert = require('assert')

describe('Testing day 4', () => {
  it('first challenge', (done) => {
    assert(should)
    assert(require('../day_4/index'))
    require('../day_4/index').isValidPassphrase('aa bb cc dd ee').should.be.equal(true)
    require('../day_4/index').isValidPassphrase('aa bb cc dd aa').should.be.equal(false)
    require('../day_4/index').isValidPassphrase('aa bb cc dd aaa').should.be.equal(true)
    require('../day_4/index').isValidPassphrase('aa bb cc dd aaa').should.be.equal(true)
    require('../day_4/index').isValidPassphrase('fyx fyx nzkm fyx').should.be.equal(false)
    require('../day_4/index').isValidPassphrase('fyx cc nzkm fyxs').should.be.equal(true)
    require('../day_4/index').howManyPassAreValid(require('../day_4/input').input).should.be.equal(451)
    done()
  })
  it('second challenge', (done) => {
    assert(should)
    assert(require('../day_4/index'))
    require('../day_4/index').checkSum('aa bb cc dd ee').should.be.equal(1118)
    require('../day_4/index').isValidCheckSum('abcde fghij').should.be.equal(true)
    require('../day_4/index').isValidCheckSum('abcde xyz ecdab').should.be.equal(false)
    require('../day_4/index').checkSum('abcde xyz ecdab').should.be.equal(1417)
    require('../day_4/index').checkSum('abcde xyz abced').should.be.equal(1417)
    require('../day_4/index').checkSum('edcba xyz abced').should.be.equal(1417)
    require('../day_4/index').isValidCheckSum('a ab abc abd abf abj').should.be.equal(true)
    require('../day_4/index').isValidCheckSum('iiii oiii ooii oooi oooo').should.be.equal(true)
    require('../day_4/index').isValidCheckSum('oiii ioii iioi iiio').should.be.equal(false)
    require('../day_4/index').isValidCheckSum('kxomfck idlh xrbowo nyetbnl qskh xuwkkxe upmmmf zhvuyp').should.be.equal(true)
    require('../day_4/index').isValidCheckSum('kxomfck kcfmoxk idlh xrbowo nyetbnl qskh xuwkkxe upmmmf zhvuyp').should.be.equal(false)
    require('../day_4/index').isValidCheckSum('drczdf bglmf gsx flcf ojpj kzrwrho owbkl dgrnv bggjevc').should.be.equal(true)
    require('../day_4/index').isValidCheckSum('wywwl scezo clowuz dkgqaj dohyzcp').should.be.equal(true)
    require('../day_4/index').isValidCheckSum('mgn gox tcifta vzc lxry gox gox mvila qdl jipjnw dvu\n').should.be.equal(false)
    require('../day_4/index').isValidCheckSum('hxk xhk unhdmdz yomze povrt nbww bxu qqsqc rvuk tgffy twddm').should.be.equal(false)
    require('../day_4/index').isValidCheckSum('fyx fyx nzkm fyx').should.be.equal(false)
    require('../day_4/index').howManyPassChecksumAreValid(require('../day_4/input').input).should.be.equal(204)
    'a'.charCodeAt(0).should.be.equal(97)
    'b'.charCodeAt(0).should.be.equal(98)
    'c'.charCodeAt(0).should.be.equal(99)
    'd'.charCodeAt(0).should.be.equal(100)
    'e'.charCodeAt(0).should.be.equal(101)
    'f'.charCodeAt(0).should.be.equal(102)
    'g'.charCodeAt(0).should.be.equal(103)
    'h'.charCodeAt(0).should.be.equal(104)
    'i'.charCodeAt(0).should.be.equal(105)
    'j'.charCodeAt(0).should.be.equal(106)
    'k'.charCodeAt(0).should.be.equal(107)
    'l'.charCodeAt(0).should.be.equal(108)
    'm'.charCodeAt(0).should.be.equal(109)
    'n'.charCodeAt(0).should.be.equal(110)
    'o'.charCodeAt(0).should.be.equal(111)
    'p'.charCodeAt(0).should.be.equal(112)
    'q'.charCodeAt(0).should.be.equal(113)
    'r'.charCodeAt(0).should.be.equal(114)
    's'.charCodeAt(0).should.be.equal(115)
    't'.charCodeAt(0).should.be.equal(116)
    'u'.charCodeAt(0).should.be.equal(117)
    'v'.charCodeAt(0).should.be.equal(118)
    'w'.charCodeAt(0).should.be.equal(119)
    'x'.charCodeAt(0).should.be.equal(120)
    'y'.charCodeAt(0).should.be.equal(121)
    'z'.charCodeAt(0).should.be.equal(122)
    done()
  })

})
