# Build Environment
build_environment: Ubuntu 16.04

# language setting
language: node_js
# version numbers, testing against two versions of node
node_js:
 - "8.9.1"

# npm install runs by default but shown here for illustrative purposes
before_install:
 - npm install -g mocha

 # Running npm test to run your test cases
script:
 - npm test

branches:
  only:
  - master

after_success:
- npm run coveralls